### ISSUE TITLE
Matching U-turns

### ISSUE THREAD

**Issue by grigoriytch** [bmwcarit/barefoot#73] opened 2017-09-20 08:02 UTC
When a U-turn is made not on a junction but on the middle of the road, the path reported by the matching algorithm is to the end of the road segment and back to current position. In this case the calculated distance is much greater (in some cases more than 1 km) than the actual traveled distance.
Is it possible to split the road segment and make the switch in direction at some point near to actual U-turn.
I'm providing a picture and test data.
![u-turn-1](https://user-images.githubusercontent.com/20398983/30633091-18114c42-9df3-11e7-9df6-bfc18b8d2307.png)
[points-1.txt](https://github.com/bmwcarit/barefoot/files/1316984/points-1.txt)

**Comment by smattheis** [comment] 2017-09-20 15:08
That's not supported at the moment. This is kind of by design for the router because it would sometimes prefer u-turns instead of "natural" routes. To illustrate this, see the image below where the design prefers A over B.

<img width="577" alt="barefoot" src="https://user-images.githubusercontent.com/7805104/30651304-9754865e-9e25-11e7-8b1d-6832bb265436.png">

However, I understand your case because it means that it also prefers C over D which is unnatural too. I could try out (so success is not guaranteed) a quick fix with a simple logic: For each determined transition (route) check its sequence of roads if it includes the opposite side segment of the start segment and if so, cut the route appropriately. That means it prefers then D over C but also still A over B. What do you think? Does it make sense to you?

**Comment by grigoriytch** [comment] 2017-09-21 07:07
Yes, this is exactly what we need.
With one more condition - if the position is near (e.g. < MaxRadius) the junction then leave the logic as is and don't cut the road.
Thank you in advance.

**Comment by smattheis** [comment] 2018-06-05 15:21
This is addressed in PR #108. I'm closing this issue now.

**Closed by smattheis** 2018-06-05 15:21 UTC
Labels: enhancement
