### ISSUE TITLE
Incorrect type for HashMap key

### ISSUE THREAD

**Issue by jongiddy** [bmwcarit/barefoot#37] opened 2017-01-11 17:31 UTC
IntelliJ IDEA identified the following line as suspicious. Should it use `containsKey(target.edge())`?

https://github.com/bmwcarit/barefoot/blob/508aaa09fa38f9b8a997316dff856d7b59421c26/src/main/java/com/bmwcarit/barefoot/topology/Dijkstra.java#L125

**Comment by smattheis** [comment] 2017-01-12 13:29
Thanks a lot, for this hint. I will check this with a unit test, and fix it. For now, I mark this issue as a bug. (Just as a side note for myself, maybe this is the root cause for this issue https://github.com/bmwcarit/barefoot/issues/27.)

**Comment by smattheis** [comment] 2017-01-19 10:39
I have verified that it's a bug, fixed it and added a short test. I will push this with some other (minor) commits soon and close this issue once it's pushed. Thanks again, for your input!

**Comment by jongiddy** [comment] 2017-05-15 09:41
Any update on the fix for this bug? I have tested some data after making the simple change above. It appeared to make no difference to the mapped co-ordinates, but it did change some road ID's. The changed id's either were at road fraction 1.0 (so intersections), or were the same road, but heading in the opposite direction (e.g. 3316370, 0.646 becoming 3316371, 0.354). Thanks.

**Comment by smattheis** [comment] 2017-06-07 16:18
Fixed in commit https://github.com/bmwcarit/barefoot/commit/7163f9f84f6c772cb5c6c5ac9dd25178090577f6 released with https://github.com/bmwcarit/barefoot/releases/tag/0.1.1

**Closed by smattheis** 2017-06-07 16:18 UTC
Labels: bug
