### ISSUE TITLE
cannot create db with default import.sh

### ISSUE THREAD

**Issue by akkou** [bmwcarit/barefoot#54] opened 2017-04-25 02:25 UTC
I followed the instruction then got this message:
```
root@acef54deeedb# bash /mnt/map/osm/import.sh
createdb: database creation failed: ERROR:  could not stat file "base/1/pg_internal.init": 
No such file or directory
```
Any guide for this? (OS : CentOS 7.3)

**Comment by smattheis** [comment] 2017-04-25 06:44
Which instructions did you follow? You mean, these: https://github.com/bmwcarit/barefoot#map-server ? Looks like something went wrong, when building the image. Have you tried deleting and rebuilding the image?

**Comment by akkou** [comment] 2017-04-25 06:47
Yes, that instruction. I deleted and rebuilt the image, too. I should try again to see if it helps.

**Comment by smattheis** [comment] 2017-04-25 13:10
I have tested the instructions with the new Docker version 17.04.0-ce, build 4845c56 which succeeded. Can you please capture the complete message log of image creation (build command) and the import and post it here?

**Comment by akkou** [comment] 2017-04-26 02:07
![2017-04-26 10 52 26](https://cloud.githubusercontent.com/assets/9050354/25415102/8eff97e2-2a70-11e7-881d-99e51c42c98b.png)

**Comment by smattheis** [comment] 2017-04-26 08:20
In this log you didn't rebuild the image because it's using image layers from cache (see "Using cache"). I would try to delete the image with `sudo docker rmi barefoot-map`(of course, you must delete depending containers first, e.g., with `sudo docker rm -f barefoot-oberbayern`), and then rebuild it with `sudo docker build -t barefoot-map ./map &> build.log`. This will save the log in the file `build.log`which you can then post or attach to this thread.

**Comment by akkou** [comment] 2017-04-27 09:07
Now, that generated a long log.
[build.txt](https://github.com/bmwcarit/barefoot/files/961039/build.txt)

**Comment by smattheis** [comment] 2017-04-27 10:21
Unfortunatenly, I can't reproduce the problem. Have you checked if the import works now after you rebuilt the image? What I can tell you and what you could check is: 

1. `base/1/pg_internal.init` refers to the process ID of some PostgreSQL process. However, your log screenshot, see `[ OK ]` indicates that the process is healthy. Nevertheless, you could check that back with `service postgresql status`.
2. For some reason, the creation of the database fails which relies on the PostgreSQL command `createdb`. You could check that back with `sudo -u postgres createdb test` and `sudo -u postgres psql -l` should show a list of the databases and include the line `test      | postgres | SQL_ASCII | C       | C     |`. (You can delete it afterwards with `sudo -u postgres dropdb test`.)

Would be nice if you keep me tuned on that. Thanks.

**Comment by smattheis** [comment] 2017-04-27 11:17
UPDATE (with friendly reference from user @crea): Could you check the SELinux status of your CentOS with `sudo sestatus`? If it says: `SELinux status: enabled`try to set it to `permissive` instead of `enabled` and reboot your host system.

**Comment by smattheis** [comment] 2017-06-07 16:27
Seems to be resolved. Closing this issue for now.

**Closed by smattheis** 2017-06-07 16:27 UTC
